import {
  Transaction,
  Budget,
  MonthlyData,
  CategoryBreakdown,
  AIInsight,
  UserProfile,
} from "@/types";

export const mockUser: UserProfile = {
  name: "Alex Thompson",
  email: "alex@financeai.com",
  joinDate: "2024-03-15",
  plan: "pro",
};

export const mockTransactions: Transaction[] = [
  {
    id: "t1",
    description: "Monthly Salary",
    amount: 8500,
    type: "income",
    category: "salary",
    date: "2025-05-01",
    merchant: "TechCorp Inc.",
    status: "completed",
  },
  {
    id: "t2",
    description: "Apartment Rent",
    amount: -2200,
    type: "expense",
    category: "housing",
    date: "2025-05-01",
    merchant: "Skyline Properties",
    status: "completed",
  },
  {
    id: "t3",
    description: "Whole Foods Market",
    amount: -156.32,
    type: "expense",
    category: "food",
    date: "2025-05-03",
    merchant: "Whole Foods",
    status: "completed",
  },
  {
    id: "t4",
    description: "Freelance Design Project",
    amount: 2400,
    type: "income",
    category: "freelance",
    date: "2025-05-04",
    merchant: "DesignHub Client",
    status: "completed",
  },
  {
    id: "t5",
    description: "Netflix Subscription",
    amount: -15.99,
    type: "expense",
    category: "entertainment",
    date: "2025-05-05",
    merchant: "Netflix",
    status: "completed",
  },
  {
    id: "t6",
    description: "Uber Rides",
    amount: -42.5,
    type: "expense",
    category: "transport",
    date: "2025-05-06",
    merchant: "Uber",
    status: "completed",
  },
  {
    id: "t7",
    description: "Apple Store",
    amount: -299.0,
    type: "expense",
    category: "shopping",
    date: "2025-05-07",
    merchant: "Apple",
    status: "completed",
  },
  {
    id: "t8",
    description: "Gym Membership",
    amount: -49.99,
    type: "expense",
    category: "health",
    date: "2025-05-08",
    merchant: "Equinox",
    status: "completed",
  },
  {
    id: "t9",
    description: "Online Course",
    amount: -79.0,
    type: "expense",
    category: "education",
    date: "2025-05-09",
    merchant: "Udemy",
    status: "completed",
  },
  {
    id: "t10",
    description: "Electricity Bill",
    amount: -128.45,
    type: "expense",
    category: "utilities",
    date: "2025-05-10",
    merchant: "ConEdison",
    status: "completed",
  },
  {
    id: "t11",
    description: "Stock Dividends",
    amount: 340.0,
    type: "income",
    category: "investment",
    date: "2025-05-11",
    merchant: "Vanguard",
    status: "completed",
  },
  {
    id: "t12",
    description: "Restaurant Dinner",
    amount: -87.5,
    type: "expense",
    category: "food",
    date: "2025-05-12",
    merchant: "Nobu",
    status: "completed",
  },
  {
    id: "t13",
    description: "Spotify Premium",
    amount: -9.99,
    type: "expense",
    category: "entertainment",
    date: "2025-05-13",
    merchant: "Spotify",
    status: "completed",
  },
  {
    id: "t14",
    description: "Gas Station",
    amount: -55.0,
    type: "expense",
    category: "transport",
    date: "2025-05-14",
    merchant: "Shell",
    status: "completed",
  },
  {
    id: "t15",
    description: "Trader Joe's",
    amount: -94.23,
    type: "expense",
    category: "food",
    date: "2025-05-14",
    merchant: "Trader Joe's",
    status: "completed",
  },
  {
    id: "t16",
    description: "Internet Bill",
    amount: -79.99,
    type: "expense",
    category: "utilities",
    date: "2025-05-15",
    merchant: "Verizon",
    status: "pending",
  },
  {
    id: "t17",
    description: "Consulting Fee",
    amount: 1200,
    type: "income",
    category: "freelance",
    date: "2025-05-15",
    merchant: "StartupXYZ",
    status: "pending",
  },
  {
    id: "t18",
    description: "Amazon Purchase",
    amount: -67.89,
    type: "expense",
    category: "shopping",
    date: "2025-05-16",
    merchant: "Amazon",
    status: "completed",
  },
  {
    id: "t19",
    description: "Pharmacy",
    amount: -32.5,
    type: "expense",
    category: "health",
    date: "2025-05-16",
    merchant: "CVS Pharmacy",
    status: "completed",
  },
  {
    id: "t20",
    description: "Coffee Shop",
    amount: -6.75,
    type: "expense",
    category: "food",
    date: "2025-05-17",
    merchant: "Blue Bottle Coffee",
    status: "completed",
  },
  {
    id: "t21",
    description: "Movie Tickets",
    amount: -28.0,
    type: "expense",
    category: "entertainment",
    date: "2025-05-11",
    merchant: "AMC Theatres",
    status: "completed",
  },
  {
    id: "t22",
    description: "Parking Fee",
    amount: -15.0,
    type: "expense",
    category: "transport",
    date: "2025-05-10",
    merchant: "ParkMobile",
    status: "completed",
  },
  {
    id: "t23",
    description: "Home Insurance",
    amount: -185.0,
    type: "expense",
    category: "housing",
    date: "2025-05-02",
    merchant: "State Farm",
    status: "completed",
  },
  {
    id: "t24",
    description: "Zara",
    amount: -124.5,
    type: "expense",
    category: "shopping",
    date: "2025-05-09",
    merchant: "Zara",
    status: "completed",
  },
  {
    id: "t25",
    description: "Water Bill",
    amount: -45.0,
    type: "expense",
    category: "utilities",
    date: "2025-05-05",
    merchant: "Water Authority",
    status: "completed",
  },
];

export const mockBudgets: Budget[] = [
  {
    id: "b1",
    category: "housing",
    name: "Housing",
    limit: 2500,
    spent: 2385,
    color: "#6366f1",
  },
  {
    id: "b2",
    category: "food",
    name: "Food & Dining",
    limit: 600,
    spent: 344.8,
    color: "#f59e0b",
  },
  {
    id: "b3",
    category: "transport",
    name: "Transportation",
    limit: 300,
    spent: 112.5,
    color: "#10b981",
  },
  {
    id: "b4",
    category: "entertainment",
    name: "Entertainment",
    limit: 200,
    spent: 53.98,
    color: "#ec4899",
  },
  {
    id: "b5",
    category: "shopping",
    name: "Shopping",
    limit: 400,
    spent: 491.39,
    color: "#8b5cf6",
  },
  {
    id: "b6",
    category: "health",
    name: "Health & Fitness",
    limit: 150,
    spent: 82.49,
    color: "#14b8a6",
  },
  {
    id: "b7",
    category: "utilities",
    name: "Utilities",
    limit: 350,
    spent: 253.44,
    color: "#f97316",
  },
  {
    id: "b8",
    category: "education",
    name: "Education",
    limit: 200,
    spent: 79.0,
    color: "#06b6d4",
  },
];

export const mockMonthlyData: MonthlyData[] = [
  { month: "Dec", income: 9200, expenses: 5800, savings: 3400 },
  { month: "Jan", income: 8800, expenses: 6200, savings: 2600 },
  { month: "Feb", income: 9500, expenses: 5500, savings: 4000 },
  { month: "Mar", income: 10200, expenses: 6800, savings: 3400 },
  { month: "Apr", income: 9800, expenses: 5900, savings: 3900 },
  { month: "May", income: 12440, expenses: 3802.6, savings: 8637.4 },
];

export const mockCategoryBreakdown: CategoryBreakdown[] = [
  { category: "Housing", amount: 2385, color: "#6366f1", percentage: 35.2 },
  { category: "Food", amount: 344.8, color: "#f59e0b", percentage: 12.8 },
  { category: "Shopping", amount: 491.39, color: "#8b5cf6", percentage: 10.5 },
  { category: "Utilities", amount: 253.44, color: "#f97316", percentage: 8.2 },
  {
    category: "Transport",
    amount: 112.5,
    color: "#10b981",
    percentage: 6.4,
  },
  { category: "Health", amount: 82.49, color: "#14b8a6", percentage: 4.8 },
  { category: "Education", amount: 79.0, color: "#06b6d4", percentage: 3.1 },
  {
    category: "Entertainment",
    amount: 53.98,
    color: "#ec4899",
    percentage: 2.8,
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    id: "ai1",
    title: "Shopping Budget Exceeded",
    description:
      "Your shopping spending is 23% over budget this month. Consider delaying non-essential purchases to stay on track.",
    type: "warning",
    impact: "high",
    category: "Budget Alert",
    actionLabel: "Review Budget",
  },
  {
    id: "ai2",
    title: "Great Savings Month!",
    description:
      "You're on track to save $8,637 this month — 69% of your income. That's your best savings rate in 6 months!",
    type: "success",
    impact: "high",
    category: "Savings",
  },
  {
    id: "ai3",
    title: "Recurring Subscription Alert",
    description:
      "You have 3 entertainment subscriptions totaling $54/month. Consider consolidating to save ~$25/month.",
    type: "tip",
    impact: "medium",
    category: "Optimization",
    actionLabel: "View Subscriptions",
  },
  {
    id: "ai4",
    title: "Income Trend Up",
    description:
      "Your freelance income has increased 35% over the last 3 months. Consider allocating the extra to investments.",
    type: "info",
    impact: "medium",
    category: "Income",
  },
  {
    id: "ai5",
    title: "Housing Cost Ratio",
    description:
      "Housing takes up 27% of your gross income, which is within the recommended 28% threshold. Well managed!",
    type: "success",
    impact: "low",
    category: "Housing",
  },
  {
    id: "ai6",
    title: "Food Spending Pattern",
    description:
      "Your dining out expenses are 2.5x your grocery spending. Cooking more meals at home could save ~$200/month.",
    type: "tip",
    impact: "medium",
    category: "Food",
    actionLabel: "See Breakdown",
  },
];

export const categoryIcons: Record<string, string> = {
  housing: "🏠",
  food: "🍽️",
  transport: "🚗",
  entertainment: "🎬",
  shopping: "🛍️",
  health: "💊",
  education: "📚",
  utilities: "⚡",
  salary: "💼",
  freelance: "💻",
  investment: "📈",
  transfer: "🔄",
  other: "📦",
};

export const categoryColors: Record<string, string> = {
  housing: "#6366f1",
  food: "#f59e0b",
  transport: "#10b981",
  entertainment: "#ec4899",
  shopping: "#8b5cf6",
  health: "#14b8a6",
  education: "#06b6d4",
  utilities: "#f97316",
  salary: "#22c55e",
  freelance: "#3b82f6",
  investment: "#a855f7",
  transfer: "#64748b",
  other: "#94a3b8",
};
